### ISSUE TITLE
2 Bugs need to fixed

### ISSUE THREAD

**Issue by ChenyangLiu** [ColumbiaDVMM/CDC#15]
Thank you for share your code, it's a really good work. But there are some problems in your project.

1. In frame_wise_softmax_loss_layer.cpp:86, you want to take into account ambiguous frame, that works fine on the dataset with ambiguous. But if I want to use this project on my data, that will be confused. I think it's better to ignore ambiguous in preprocess, not in caffe layer.

2. During my training, I found that some -nan appears randomly, even I set my lr=1e-9. And I find that there is a typo in voxel_wise_softmax_layer.cpp:66.
It should be max(scale_data[scale_.offset(i,0,l,h,w)],
since the bottom[0] and the scale_ have different shape. It may subtract a huge number in the next step, and -nan appears.

**Comment by zhengshou** [comment]
Thank you so much for reporting the concerns and issues. Will look into it soon in the following days. Thanks.
