### ISSUE TITLE
how to download the source code?

### ISSUE THREAD

**Issue by timbryant** [ColumbiaDVMM/CDC#18]
hi,Thank you for you hard working, I'm very interested in your work
In your README said,we can find the source code through: https://bitbucket.org/columbiadvmm/cdc
but when I opened the wibesite, I havn't find the source code of the CDC, and I just found the C3D and the caffe, there isn't some sorce code about the CDC.
Could yo tell me where to download the source code ?
Best wishes
I'm looking forwar for your relply, thank you very much

**Comment by zhengshou** [comment]
The source code has incorporated CDC into our C3D.
