### ISSUE TITLE
About inference speed

### ISSUE THREAD

**Issue by Qinying-Liu** [ColumbiaDVMM/CDC#21]
It is mentioned that your speed can reached at around 500 fps. I wonder how you compute the speed. Does it include the time of frames reading and pre-processing before input to the CDC becuse it is usually time-consuming? Hope to receive your reply soon.

**Comment by bityangke** [comment]
I do not think the inference time here include the pre-reprocessing time. Just feed N samples to the model and calculate the average speed (You can use a batch size).

**Comment by zhengshou** [comment]
It's running time of caffe part so include pre-processing implemented in caffe but not the part such as generating binary input files beforehand.
