### ISSUE TITLE
Do I need to download and compile both caffe and C3D before compling this CDC project?

### ISSUE THREAD

**Issue by coolbay** [ColumbiaDVMM/CDC#22]

**Comment by coolbay** [comment]
Do I need to download and compile both caffe and C3D before compling this CDC project? 

I find I cannot run `cd demo; ./xfeat.sh` successfully after directly compling CDC. It gives me the error `./xfeat.sh: line 8: ../CDC/build/tools/extract_image_features.bin: No such file or directory
`.  There isn't `extract_image_features.bin` in the directory, but there is just an `extract_image_features.o` file after I make CDC via `cd ./CDC/; make all` as instructed. 

Do I need to install caffe and C3D first?

Thank you!

**Comment by zhengshou** [comment]
You don't need to install caffe or C3D. You program cannot find
../CDC/build/tools/extract_image_features.bin which means it's not
compiled or your running root directory is incorrect
